kong-lb:
  ports:
  - 7946:7946
  - 8000:8000
  - 8001:8001
  - 8443:8443
  tty: true
  image: rancher/load-balancer-service
  links:
  - kong:kong
  stdin_open: true
kong-database:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  image: cassandra:2.2
  stdin_open: true
kong:
  environment:
    KONG_LOG_LEVEL: debug
    KONG_DATABASE: cassandra
    KONG_CASSANDRA_CONTACT_POINTS: kong-database
    KONG_PG_HOST: kong-database
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: kong:0.9.8
  links:
  - 'kong-database:'
  stdin_open: true